---

- name: Ensure base Prowlarr directory exists
  ansible.builtin.file:
    path: "{{ prowlarr_docker_base_directory }}"
    state: 'directory'
    owner: "{{ prowlarr_docker_user }}"
    group: "{{ prowlarr_docker_user }}"
    mode: '0755'
  tags:
    - prowlarr
    - prowlarr_setup

- name: Ensure Prowlarr compose file is present
  ansible.builtin.template:
    src: 'compose.yml.j2'
    dest: "{{ prowlarr_docker_base_directory }}/compose.yml"
    owner: "{{ prowlarr_docker_user }}"
    group: "{{ prowlarr_docker_user }}"
    mode: '0644'
    backup: true
  register: prowlarr_docker_compose_template_result
  tags:
    - prowlarr
    - prowlarr_config

- name: Ensure Prowlarr compose project is deployed
  community.docker.docker_compose_v2:
    project_src: "{{ prowlarr_docker_base_directory }}"
    state: 'present'
    recreate: "{{ 'always' if (prowlarr_docker_compose_template_result.changed) else 'auto' }}"
    remove_orphans: true
  tags:
    - prowlarr
    - prowlarr_deploy
