---

- name: Ensure base Prowlarr directory exists
  ansible.builtin.file:
    path: "{{ prowlarr_docker_base_directory }}"
    state: 'directory'
    owner: "{{ prowlarr_docker_user }}"
    group: "{{ prowlarr_docker_user }}"
    mode: '0755'

- name: Ensure Prowlarr compose file is present
  ansible.builtin.template:
    src: 'compose.yml.j2'
    dest: "{{ prowlarr_docker_base_directory }}/compose.yml"
    owner: "{{ prowlarr_docker_user }}"
    group: "{{ prowlarr_docker_user }}"
    mode: '0644'
    backup: true
  register: prowlarr_docker_compose_template_result

- name: Ensure Prowlarr compose project is deployed
  community.docker.docker_compose_v2:
    project_src: "{{ prowlarr_docker_base_directory }}"
    state: 'present'
    pull: "{{ 'always' if prowlarr_docker_update_image else prowlarr_docker_pull_policy }}"
    recreate: "{{ 'always' if (prowlarr_docker_compose_template_result.changed or prowlarr_docker_update_image) else 'auto' }}"
    remove_orphans: true
